<?php 
echo md5('4dm1ninfoactiva')."<br>";
// echo md5('123456')."<br>";
// echo md5('123')."<br>";
// echo md5('123')."<br>";
// echo md5('puto')."<br>";
// echo md5('123')."<br>";
// echo md5(123)."<br>";
// echo md5(123)."<br>";
// echo md5('PASSCONSULTOR')."<br>";
// echo md5('a*TBlukRy.')."<br>";
// echo md5('a*TBlukRy.')."<br>";
// echo md5('t*EBlukRy/')."<br>";
// echo md5('c*TBlakRx.')."<br>";
// echo md5('a/TBlekRy*')."<br>";
// echo md5('S/EwokPy,')."<br>";
// echo md5('O*JFq.adRt')."<br>";
// echo md5('La*7Bj2Pq.')."<br>";
// echo md5('aEl\IOrS*N')."<br>";
// echo md5('iEl\vOrS*NB')."<br>";
// echo md5('Lw/7Bj2Pq*')."<br>";
// echo md5('Ea*7Bj2Pq/')."<br>";
// echo md5('Lx/4Bh2Ps*')."<br>";
// echo md5('Ly*4Be2Pd.')."<br>";
// echo md5('PAdeHUl3')."<br>";
// echo md5(123456)."<br>";
// echo md5('123456')."<br>";
// echo md5(123456)."<br>";
// echo md5(2525)."<br>";
 ?>